/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_JniUtils */

#ifndef _Included_com_example_myapplication_JniUtils
#define _Included_com_example_myapplication_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_JniUtils
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_JniUtils_getStrFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
